version: 2
updates:

### GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
    assignees:
      - sualeh
      
### Java      
  - package-ecosystem: maven
    directory: "/Java"
    target-branch: main
    schedule:
      interval: "weekly"
      day: "friday"
    assignees:
      - sualeh
  - package-ecosystem: maven
    directory: "/Java"
    target-branch: step1
    schedule:
      interval: "weekly"
      day: "friday"
    assignees:
      - sualeh
  - package-ecosystem: maven
    directory: "/Java"
    target-branch: step2
    schedule:
      interval: "weekly"
      day: "friday"
    assignees:
      - sualeh
  - package-ecosystem: maven
    directory: "/Java"
    target-branch: step3
    schedule:
      interval: "weekly"
      day: "friday"
    assignees:
      - sualeh
  - package-ecosystem: maven
    directory: "/Java"
    target-branch: step4
    schedule:
      interval: "weekly"
      day: "friday"
    assignees:
      - sualeh
      
##### C#       
  - package-ecosystem: nuget
    directory: "/C#"
    target-branch: main
    schedule:
      interval: "weekly"
      day: "friday"
    assignees:
      - sualeh
      - nikhiltjha 
  - package-ecosystem: nuget
    directory: "/C#"
    target-branch: step1
    schedule:
      interval: "weekly"
      day: "friday"
    assignees:
      - sualeh
      - nikhiltjha 
  - package-ecosystem: nuget
    directory: "/C#"
    target-branch: step2
    schedule:
      interval: "weekly"
      day: "friday"
    assignees:
      - sualeh
      - nikhiltjha 
  - package-ecosystem: nuget
    directory: "/C#"
    target-branch: step3
    schedule:
      interval: "weekly"
      day: "friday"
    assignees:
      - sualeh
      - nikhiltjha 
  - package-ecosystem: nuget
    directory: "/C#"
    target-branch: step4
    schedule:
      interval: "weekly"
      day: "friday"
    assignees:
      - sualeh
      - nikhiltjha 
