version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    target-branch: main
    schedule:
      interval: "weekly"
      day: "friday"
    assignees:
      - sualeh
  - package-ecosystem: maven
    directory: "/"
    target-branch: step1
    schedule:
      interval: "weekly"
      day: "friday"
    assignees:
      - sualeh
  - package-ecosystem: maven
    directory: "/"
    target-branch: step2
    schedule:
      interval: "weekly"
      day: "friday"
    assignees:
      - sualeh
  - package-ecosystem: maven
    directory: "/"
    target-branch: step3
    schedule:
      interval: "weekly"
      day: "friday"
    assignees:
      - sualeh
  - package-ecosystem: maven
    directory: "/"
    target-branch: step4
    schedule:
      interval: "weekly"
      day: "friday"
    assignees:
      - sualeh
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
    assignees:
      - sualeh
